'use strict';
const key='aris-mobile-v1';
let data;
try {data=JSON.parse(localStorage.getItem(key)||'{}');} catch {data={};}
if(!data || typeof data!=='object' || Array.isArray(data))data={};
data.tasks=Array.isArray(data.tasks)?data.tasks:[];data.notes=Array.isArray(data.notes)?data.notes:[];
const $=id=>document.getElementById(id);
const save=()=>{try{localStorage.setItem(key,JSON.stringify(data));}catch{toast('ذخیره‌سازی در این مرورگر ممکن نیست')}};
const toast=s=>{const t=$('toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3000)};
function tab(name){document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s.id===name));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===name));window.scrollTo(0,0)}
window.tab=tab;document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function render(){ $('taskCount').textContent=String(data.tasks.filter(x=>!x.done).length);$('noteCount').textContent=String(data.notes.length);const tasks=$('taskList');tasks.replaceChildren();if(!data.tasks.length)tasks.textContent='هنوز وظیفه‌ای ثبت نشده است.';data.tasks.forEach((t,i)=>{const d=document.createElement('div');d.className='item'+(t.done?' done':'');const label=document.createElement('span');label.textContent=t.text;const actions=document.createElement('div');actions.style.display='flex';actions.style.gap='5px';const done=document.createElement('button');done.textContent=t.done?'↶':'✓';done.setAttribute('aria-label','تغییر وضعیت');done.onclick=()=>{t.done=!t.done;save();render()};const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','حذف');del.onclick=()=>{if(confirm('وظیفه حذف شود؟')){data.tasks.splice(i,1);save();render()}};actions.append(done,del);d.append(label,actions);tasks.append(d)});const notes=$('noteList');notes.replaceChildren();if(!data.notes.length)notes.textContent='هنوز یادداشتی ثبت نشده است.';data.notes.forEach((n,i)=>{const p=document.createElement('div');p.className='panel';const h=document.createElement('h3');h.textContent=n.title;const body=document.createElement('p');body.style.whiteSpace='pre-wrap';body.style.overflowWrap='anywhere';body.textContent=n.body;const del=document.createElement('button');del.className='secondary';del.textContent='حذف';del.onclick=()=>{if(confirm('یادداشت حذف شود؟')){data.notes.splice(i,1);save();render()}};p.append(h,body,del);notes.append(p)})}
$('addTask').onclick=()=>{const t=$('taskInput').value.trim();if(!t)return toast('متن وظیفه را وارد کن');data.tasks.unshift({text:t,done:false});$('taskInput').value='';save();render()};$('taskInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('addTask').click()});
$('addNote').onclick=()=>{const title=$('noteTitle').value.trim(),body=$('noteBody').value.trim();if(!title||!body)return toast('عنوان و متن را وارد کن');data.notes.unshift({title,body});$('noteTitle').value='';$('noteBody').value='';save();render();toast('یادداشت ذخیره شد')};
$('send').onclick=()=>{const msg=$('chatInput').value.trim();if(!msg)return;const add=(s,me)=>{const el=document.createElement('div');el.className='bubble'+(me?' me':'');el.textContent=s;$('messages').append(el);$('messages').scrollTop=$('messages').scrollHeight};add(msg,true);$('chatInput').value='';add('پیامت دریافت شد. این نسخه هنوز به مدل هوش مصنوعی متصل نیست؛ پاسخ هوشمند تولید نمی‌کنم.',false)};$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('send').click()});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aris-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)};
$('clear').onclick=()=>{if(confirm('تمام وظایف و یادداشت‌ها از این مرورگر حذف شوند؟')){data={tasks:[],notes:[]};save();render();toast('داده‌ها حذف شدند')}};
function connectionStatus(){const el=$('connectionStatus');if(el)el.textContent=navigator.onLine?'مرورگر آنلاین است':'مرورگر آفلاین است';}
window.addEventListener('online',connectionStatus);window.addEventListener('offline',connectionStatus);connectionStatus();
render();if('serviceWorker' in navigator && location.protocol==='https:')navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offlineStatus').textContent='آماده استفاده آفلاین';}).catch(()=>{$('offlineStatus').textContent='ذخیره آفلاین فعال نشد؛ صفحه را دوباره باز کن';});
